#!/bin/bash
#
# exit with a number superior to INT_MAX

command="exit 12345678999999"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file

# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c ": 1: exit: Illegal number: 12345678999999"`
if [ $nmatch -eq 1 ]; then
     print_ok
else
	print_ko
fi

# clean up
stop_shell
rm -f $tmp_file